### ISSUE TITLE
The trello board / idea collection

### ISSUE THREAD

**Issue by lenntt** [les-tontons-crafters/xtrem-tdd#10]
The [pull request template](https://github.com/les-tontons-crafters/xtrem-tdd/blob/main/.github/pull_request_template.md) mentions contributing to the trello board, but it isnt mentioned elsewhere how to find this Trello board.

I think we'd benefit from having discussions on what to add and what not - before investing in writing a page. 
e.g. Should we explain TDD? F.I.R.S.T. testing principles? coding conventions? what about model-based testing?

**Comment by ythirion** [comment]
Hi @lenntt,
Thanks for your interest in this repository, it is a very good question. 
We have a basic trello account and not able to share a public link easily...
I added you on it (if you have the same username on Atlassian).

Indeed, we have more code related topics now like you mentioned in the backlog for now.
We are clearly opened to contribution in the board.

Now we have a few contributors it would be easiest to collaborate/communicate through a dedicated channel.
I have just created a Discord server for that.
You can join it here: https://discord.gg/YdTeXr48
I will share the trello board link on it.

See you there
