### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by valentinajemuovic** [les-tontons-crafters/xtrem-tdd#17]
Could you add some licence file for the project? Preferably something that allows both commercial and non-commercial usage - e.g. MIT Licence.

As general context: I found the website useful and sometimes in client engagements, when doing an intro for some topic, I sometimes used this website to send to teams to read here.

Thanks in advance!

**Comment by ythirion** [comment]
Thanks Valentina.
Indeed, it was not clear on both the website and the repository.

It has been fixed on the website, at the bottom of each pages you will see the logo of the CC-BY-SA License.
As well on the repository itself there is a link on the details of the License.

Thanks for your feedback.
See you soon.
